### ISSUE TITLE
Arrays shouldn't allow mixed data types

### ISSUE THREAD

**Issue by justgage** [zamith/tomlex#2]
First off, good job so far on this! 

I was looking through your tests and found that you had mixed data types in an array, which is valid in a lot of programing languages, but sadly the spec says that this shouldn't be allowed. (In this section)[https://github.com/toml-lang/toml#array]. I don't know if this is really big enough problem to change it. The only problem I can see is not having TOML that would be compatible with languages like Java which don't allow types to be mixed.

**Comment by zamith** [comment]
Thanks for the issue, I had completely missed this when I read through the specs.

I do think tomlex should enforce this, I'll add it to the roadmap but assign it a low priority. I'll also add a warning to the README, saying that it is allowed right now, but will be disallowed in the future.

Other than stuff already on the roadmap, please let me know if you find any issues.
